export const ROUTES = {
  HOME: "/",
  GAMES: "/games",
  GAME_DETAIL: "/games/:id",
  COMPARE: "/compare",
  ABOUT: "/about",
  FAVORITES: "/favorites",
  PROFILE: "/profile",
  LOGIN: "/login",
  SIGNUP: "/signup",
  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_GAMES: "/admin/games",
  ADMIN_GAME_DETAIL: "/admin/games/:id",
  ADMIN_COMPARISONS: "/admin/comparisons",
  ADMIN_SETTINGS: "/admin/settings",
};
