export const API_ROUTES = {
  AUTH: {
    LOGIN: "/api/auth/login",
    REGISTER: "/api/auth/register",
  },
  USERS: {
    ME: "/api/users/me",
    GET_ALL: "/api/users/list",
    GET_BY_ID: (id: number) => `/api/users/${id}`,
    CREATE: "/api/users/create",
    UPDATE: (id: number) => `/api/users/${id}`,
    DELETE: (id: number) => `/api/users/${id}`,
    CHANGE_PASSWORD: "/api/users/changePassword",
    UPDATE_PROFILE: "/api/users/updateProfile",
  },
  GAMES: {
    GET_ALL: '/api/game',
    GET_BY_ID: (id: number) => `/api/game/${id}`,
    COMPARE: (ids: number[]) => `/api/game/compare?ids=${ids.join(',')}`,
    CREATE: '/api/game',
    UPDATE: (id: number) => `/api/game/${id}`,
    DELETE: (id: number) => `/api/game/${id}`,
  },
  GENRES: {
    GET_ALL: '/api/genre',
    GET_BY_ID: (id: number) => `/api/genre/${id}`,
    CREATE: '/api/genre',
    UPDATE: (id: number) => `/api/genre/${id}`,
    DELETE: (id: number) => `/api/genre/${id}`,
  },
  PLATFORMS: {
    GET_ALL: '/api/platform',
    GET_BY_ID: (id: number) => `/api/platform/${id}`,
    CREATE: '/api/platform',
    UPDATE: (id: number) => `/api/platform/${id}`,
    DELETE: (id: number) => `/api/platform/${id}`,
  },
  GAME_MODES: {
    GET_ALL: '/api/gamemode',
    GET_BY_ID: (id: number) => `/api/gamemode/${id}`,
    CREATE: '/api/gamemode',
    UPDATE: (id: number) => `/api/gamemode/${id}`,
    DELETE: (id: number) => `/api/gamemode/${id}`,
  },
  RATINGS: {
    GET_BY_GAME: (gameId: number) => `/api/rating/game/${gameId}`,
    GET_MY_RATING: (gameId: number) => `/api/rating/my/${gameId}`,
    CREATE: '/api/rating',
  },
  FAVORITES: {
    GET_ALL: '/api/favorite',
    ADD: (gameId: number) => `/api/favorite/${gameId}`,
    REMOVE: (gameId: number) => `/api/favorite/${gameId}`,
    EXISTS: (gameId: number) => `/api/favorite/${gameId}/exists`,
  },
  PROFILE: {
    GET: '/api/profile',
    UPDATE: '/api/profile',
  },
};
