// <auto-generated />
using System;
using Diffy.DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Diffy.DataAccessLayer.Migrations
{
    [DbContext(typeof(DiffyDbContext))]
    [Migration("20260511085828_AddGameImgs")]
    partial class AddGameImgs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An open-world RPG set in a dark fantasy universe.",
                            Developer = "CD Projekt Red",
                            Price = 29.99m,
                            Publisher = "CD Projekt",
                            ReleaseYear = 2015,
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An action RPG set in a vast open world created by Hidetaka Miyazaki and George R. R. Martin.",
                            Developer = "FromSoftware",
                            Price = 59.99m,
                            Publisher = "Bandai Namco",
                            ReleaseYear = 2022,
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 3,
                            Description = "An open-world action RPG set in the megalopolis of Night City.",
                            Developer = "CD Projekt Red",
                            Price = 39.99m,
                            Publisher = "CD Projekt",
                            ReleaseYear = 2020,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A rogue-like dungeon crawler where you play as the son of the god of the dead.",
                            Developer = "Supergiant Games",
                            Price = 24.99m,
                            Publisher = "Supergiant Games",
                            ReleaseYear = 2020,
                            Title = "Hades"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A farming simulation RPG where you build and manage your own farm.",
                            Developer = "ConcernedApe",
                            Price = 14.99m,
                            Publisher = "ConcernedApe",
                            ReleaseYear = 2016,
                            Title = "Stardew Valley"
                        });
                });

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GameGameModeEntity", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("GameModeId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "GameModeId");

                    b.HasIndex("GameModeId");

                    b.ToTable("GameGameModes");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GameModeId = 1
                        },
                        new
                        {
                            GameId = 2,
                            GameModeId = 1
                        },
                        new
                        {
                            GameId = 2,
                            GameModeId = 2
                        },
                        new
                        {
                            GameId = 3,
                            GameModeId = 1
                        },
                        new
                        {
                            GameId = 4,
                            GameModeId = 1
                        },
                        new
                        {
                            GameId = 5,
                            GameModeId = 1
                        },
                        new
                        {
                            GameId = 5,
                            GameModeId = 3
                        });
                });

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GameGenreEntity", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 5
                        });
                });

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GameImgEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameImgs");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GamePlatformEntity", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatforms");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            PlatformId = 1
                        },
                        new
                        {
                            GameId = 1,
                            PlatformId = 2
                        },
                        new
                        {
                            GameId = 2,
                            PlatformId = 1
                        },
                        new
                        {
                            GameId = 2,
                            PlatformId = 2
                        },
                        new
                        {
                            GameId = 2,
                            PlatformId = 3
                        },
                        new
                        {
                            GameId = 3,
                            PlatformId = 1
                        },
                        new
                        {
                            GameId = 3,
                            PlatformId = 2
                        },
                        new
                        {
                            GameId = 4,
                            PlatformId = 1
                        },
                        new
                        {
                            GameId = 4,
                            PlatformId = 4
                        },
                        new
                        {
                            GameId = 5,
                            PlatformId = 1
                        },
                        new
                        {
                            GameId = 5,
                            PlatformId = 4
                        });
                });

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GameRatingEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("GameRatings");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.GameModeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameModes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single Player"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Multiplayer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Co-op"
                        });
                });

            modelBuilder.Entity("Diffy.Domain.Entities.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Simulation"
                        });
                });

            modelBuilder.Entity("Diffy.Domain.Entities.PlatformEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PlayStation 5"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Xbox Series X"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nintendo Switch"
                        });
                });

            modelBuilder.Entity("Diffy.Domain.Entities.User.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.User.UserFavoriteEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.User.UserProfileEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("CpuModel")
                        .HasColumnType("text");

                    b.Property<string>("GpuModel")
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<string>("PlatformVersion")
                        .HasColumnType("text");

                    b.Property<int?>("RamGb")
                        .HasColumnType("integer");

                    b.Property<int?>("StorageGb")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GameGameModeEntity", b =>
                {
                    b.HasOne("Diffy.Domain.Entities.Game.GameEntity", "Game")
                        .WithMany("GameModes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diffy.Domain.Entities.GameModeEntity", "GameMode")
                        .WithMany()
                        .HasForeignKey("GameModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameMode");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GameGenreEntity", b =>
                {
                    b.HasOne("Diffy.Domain.Entities.Game.GameEntity", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diffy.Domain.Entities.GenreEntity", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GameImgEntity", b =>
                {
                    b.HasOne("Diffy.Domain.Entities.Game.GameEntity", "Game")
                        .WithMany("Imgs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GamePlatformEntity", b =>
                {
                    b.HasOne("Diffy.Domain.Entities.Game.GameEntity", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diffy.Domain.Entities.PlatformEntity", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GameRatingEntity", b =>
                {
                    b.HasOne("Diffy.Domain.Entities.Game.GameEntity", "Game")
                        .WithMany("Ratings")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diffy.Domain.Entities.User.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.User.UserFavoriteEntity", b =>
                {
                    b.HasOne("Diffy.Domain.Entities.Game.GameEntity", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diffy.Domain.Entities.User.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.User.UserProfileEntity", b =>
                {
                    b.HasOne("Diffy.Domain.Entities.User.UserEntity", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("Diffy.Domain.Entities.User.UserProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.Game.GameEntity", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("GameModes");

                    b.Navigation("GamePlatforms");

                    b.Navigation("Imgs");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.GenreEntity", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.PlatformEntity", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("Diffy.Domain.Entities.User.UserEntity", b =>
                {
                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
