<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diffy.DataAccessLayer\Diffy.DataAccessLayer.csproj" />
    <ProjectReference Include="..\Diffy.Domain\Diffy.Domain.csproj" />
  </ItemGroup>

</Project>
